### Pandas : Sort, Aggregation, GroupBy
1. `$DataFrame.sort_values()` : 
	- parameters : by=[columns], inplace=False, ascending=False0

2. Aggregation(데이터 집계) : 여러 개의 레코드 값을 요약하여 하나의 통계값(합계, 평균, 최댓값 등)으로 변환하는 작업
	- `$DataFrame.count()`, `$DataFrame.sum()`, `$DataFrame.max()` 등
	- 특정 컬럼으로 필터링을 한 뒤에 사용하는게 아니라면, DataFrame내의 모든 컬럼에 대해서 적용한다.
	

3. `$DataFrame.GroupBy()`
	- 해당 메서드 호출 시 Index가 Group기준이 된다.
	- 반환값은 Grouping된 DataFrame인 `DataFrameGroupBy`인스턴스이다.
	- `DataFrameGroupBy` 인스턴스에 인덱싱을 활용해서 원하는 컬럼만 뽑아낸 뒤 Aggregation을 수행하면 좋다.

### Practice : DataFrame을 특정 열을 기준으로(by) 정렬하기

In [8]:
import pandas as pd

titanic_df = pd.read_csv('titanic_train.csv')
sorted_df = titanic_df.sort_values(by=['Age'], inplace=False, ascending=True)

display(sorted_df.head(3))

sorted_df2 = titanic_df.sort_values(by=['Pclass', 'Age'], inplace=False, ascending=True)
display(sorted_df2.head())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
297,298,0,1,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
445,446,1,1,"Dodge, Master. Washington",male,4.00,0,2,33638,81.8583,A34,S
802,803,1,1,"Carter, Master. William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S
435,436,1,1,"Carter, Miss. Lucile Polk",female,14.00,1,2,113760,120.0000,B96 B98,S

### Practice : Data Aggregation 수행하기
- count(), max(), min() 등

In [14]:
import pandas as pd

titanic_df = pd.read_csv('titanic_train.csv')

print(titanic_df.count(), end='\n\n')

print(titanic_df[['Age', 'Fare']].max())

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

Age      80.0000
Fare    512.3292
dtype: float64

### Practice: GroupBy() 적용

In [22]:
import pandas as pd

titanic_df = pd.read_csv('titanic_train.csv')
titanic_df.groupby(by='Pclass').count()

titanic_df.groupby(by='Pclass')[['Age', 'Fare']].count()

titanic_df.groupby(by='Pclass')['Age'].agg([max, min])


agg_format = {'Age':'max', 'SibSp': 'sum', 'Fare':'mean'}
titanic_df.groupby(by='Pclass').agg(agg_format)

/var/folders/c1/h7bpvp6j477dywpxvwgcb5qw0000gn/T/ipykernel_63518/3277188633.py:8: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  titanic_df.groupby(by='Pclass')['Age'].agg([max, min])
/var/folders/c1/h7bpvp6j477dywpxvwgcb5qw0000gn/T/ipykernel_63518/3277188633.py:8: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  titanic_df.groupby(by='Pclass')['Age'].agg([max, min])

         Age  SibSp       Fare
Pclass
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550