### Pandas 1: Pandas의 주요 객체 이해하기
- Pandas는 행과 열로 이루어진 2차원 데이터를 효율적으로 가공/처리할 수 있게 만드는 라이브러리이다.

1. Index
	- 개별 데이터를 고유하게 식별하는 Key값
	- Series와 DataFrame은 모두 Index를 Key값으로 가진다.
2. Series
	- 컬럼 하나를 Series라고 부른다.
	- Series의 각 행에도 고유한 Index값이 할당되어 있다.
3. DataFrame
	- 1개 이상의 Series를 가지는 데이터 구조이다.
	- 각 행을 Record라고 부르고, 각 Record에는 고유한 Index값이 할당되어 있다.

- 각 Series는 내부적으로 (Index, Data) 형태의 쌍(Pair)을 들고있다. 이 때, 두 Series를 합쳐 DataFrame을 생성하는 경우, Pandas는 두 Series의 Index 값을 비교하여 동일한 Index를 가진 데이터끼리 같은 행(Row)으로 묶어줍니다.
	- 만약 두 Series의 Index가 서로 다르다면
		1. 순서가 다를 때는 Pandas는 데이터의 위치(순서)가 아니라 Index의 값을 기준으로 병합하므로, 순서가 섞여 있어도 알아서 인덱스를 매칭하여 정렬합니다.
		2. 일부 인덱스가 누락/불일치할 때는, 두 Series가 가진 Index의 합집합(Union)을 기준으로 DataFrame의 행이 만들어집니다. 한쪽 Series에만 존재하는 인덱스가 있다면, 해당 값이 없는 쪽에는 결측치인 NaN (Not a Number)이 채워집니다.

In [ ]:
import pandas as pd

df = pd.read_csv('titanic_train.csv')
display(df)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### Pandas methods
1. `DataFrame.head(n)`
	- DataFrame의 앞에서 n개의 데이터 출력하기
	- n을 명시하지 않는 경우, default로 n = 5이다.

2. `DataFrame.shape`
	- DataFrame의 행과 열의 개수를 튜플 형태로 반환

3. `DataFrame.info()`
	- 해당 DataFrame의 구조를 보여준다.
	- RangeIndex : 전체 몇개의 entries(record, row)가 있고, 몇개의 Feature(column)을 가지는지 보여주는 항목
	- 각 컬럼의 이름, 특정 컬럼의 non-null인 데이터의 개수, 특정 컬럼이 저장하는 데이터의 타입 등의 정보를 보여준다.

4. `DataFrame.describe()`
	- 숫자형 컬림의 통계적인 특성을 조사하는 메서드로, object 타입의 컬럼은 출력에서 제외된다.
	- 출력하는 정보는 n-percentile 분포도, 평균값, 최댓값, 최솟값을 보여준다.
	- 숫자형 카테고리 컬럼 여부를 판단하는 경우 유용하다.

5. `DataFrame.value_counts()` or `Series.value_counts()`
	- 해당 시리즈에 저장된 값의 종류와 각 값의 개수를 출력해준다.
	- 이 때, 값의 개수가 큰 종류부터 내림차순으로 정렬된 Series를 반환한다.
	- 기본적으로 해당 메서드는 Nan값은 drop해서 카운팅한다. 주의하도록 하자.

### Practice1 : `DataFrame.head(n)`

In [ ]:
import pandas as pd

df = pd.read_csv('titanic_train.csv')
display(df.head(3))

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

(891, 12)

### Practice2 : shape

In [ ]:
import pandas as pd

df = pd.read_csv('titanic_train.csv')
df.shape # tuple

(891, 12)

### Practice3 : `DataFrame.info()`

In [9]:
import pandas as pd

df = pd.read_csv('titanic_train.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

### Practice4 : `DataFrame.describe()`

In [10]:
import pandas as pd

df = pd.read_csv('titanic_train.csv')
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

### Practice5 : `Series.value_counts()`

In [ ]:
import pandas as pd

df = pd.read_csv('titanic_train.csv')
pclass_series = df['Pclass']
print(pclass_series.value_counts())

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [18]:
import pandas as pd

df = pd.read_csv('titanic_train.csv')
pclass_series = df['Embarked']
print(pclass_series.value_counts())
print(pclass_series.value_counts(dropna=False))

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64
Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64